name: photoframer
version: 1.0.0+1
publish_to: none
description: an app designed to make frame for your photo.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  exif: ^3.1.4
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  image_gallery_saver: ^2.0.3
  share_plus: ^7.1.0
  intl: ^0.19.0
  dynamic_color: ^1.6.7
  google_fonts: ^6.1.0
  geocoding: ^2.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_staggered_grid_view: ^0.7.0
  like_button: ^2.0.5
  permission_handler: ^11.0.1

dev_dependencies: 
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter: 
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
    - family: CourierPrime
      fonts:
        - asset: fonts/CourierPrime-Regular.ttf
          weight: 400
        - asset: fonts/CourierPrime-Bold.ttf
          weight: 700
  assets:
    - lib/app/data/asset/images/
    - lib/app/data/asset/rive/


